version: '3.8'

services:
  api1:
    build: ./api
    environment:
      - PORT=3001
    ports:
      - "3001:3000"

  api2:
    build: ./api
    environment:
      - PORT=3002
    ports:
      - "3002:3000"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8081:80"
    depends_on:
      - api1
      - api2