version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home  
    environment:
      - JENKINS_OPTS=--httpPort=8080


volumes:
  jenkins_home:  

# aqui se ejecuta con el comando  docker compose up -d


# este es ejemplo del anterior ejercicio en clase
 # web:
    #image: nginx:alpine
    #ports:
      #- "4000:80"  
    #volumes:
     # - ./html:/usr/share/nginx/html:ro  
